server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://47.96.76.101:3306/micro_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false"
    username: root
    password: Szw159421
  application:
    name: micro-order
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.94.132:8848
    sentinel:
      transport:
        port: 9999
        dashboard: localhost:8080
serverUrl: http://micro-product/
